#
# SPDX-FileCopyrightText: 2022 Wesley Schwengle <wesley@opperschaap.net>
#
# SPDX-License-Identifier: BSD-3-Clause
#

image: docker:stable
services:
  - docker:dind

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

stages:
  - build
  - test
  - release

license-check:
  stage: release
  script:
    - docker pull fsfe/reuse:latest
    - docker run -v $(pwd):/data fsfe/reuse:latest lint

