#!/bin/sh
#
# SPDX-FileCopyrightText: 2022 Wesley Schwengle <wesley@opperschaap.net>
#
# SPDX-License-Identifier: Unlicense
#

if [ echo "$@" | egrep -vq -- '-t|--tag' ]
then
    ARGS="-t connectiq-sdk:latest"
fi

docker build \
  --tag=connectiq-sdk:latest \
  --build-arg CIQ_SDK_UID=$(id -u) \
  --build-arg CIQ_SDK_GID=$(id -g) \
  $@ \
  .
