#
# SPDX-FileCopyrightText: 2022 Wesley Schwengle <wesley@opperschaap.net>
#
# SPDX-License-Identifier: Unlicense
#
version: '3.6'
services:
  reuse:
    image: fsfe/reuse:latest
    command:
      - lint
    volumes:
      - ./:/data

  connectiq:
    build:
      context: .
      dockerfile: Dockerfile
      target: sdk
      args:
        CIQ_SDK_UID: $CIQ_SDK_UID
        CIQ_SDK_GID: $CIQ_SDK_GID
    environment:
      DISPLAY: $DISPLAY
      XAUTHORITY: /home/ciq/.Xauthority
      CIQ_DEVICE: Your device
      MY_PROJECT: Your project name
      CIQ_API: 1.0.0
      CIQ_TYPECHECK: 0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/ciq/.Xauthority:ro
      - $HOME/.Garmin/ConnectIQ:/home/ciq/.Garmin/ConnectIQ
      - ./:/home/ciq/src

networks:
  default:
