#!/bin/bash
#
# SPDX-FileCopyrightText: 2022 Wesley Schwengle <wesleys@opperschaap.net>
#
# SPDX-License-Identifier: Unlicense
#

mkdir -p $HOME/.Garmin/ConnectIQ/.local

echo "$@" | grep -Eq -- "-t|--tags"
[ $? -ne 0 ] && ARGS="-t connectiq-sdk:latest"

docker build \
  --build-arg CIQ_SDK_UID=$(id -u) \
  --build-arg CIQ_SDK_GID=$(id -g) \
  $ARGS \
  $@ \
  .
